import json, os

#The admin-ec2-config.json is manually created/edited with account and vpc details.
configFile = 'admin-ec2-config.json'
#The script-admin-security-group-id.json file is generated by /security-groups/create_admin_security_group.sh
securityGroupFile = 'security-groups/script-admin-security-group-id.json'
f = open(configFile)
configData = json.load(f)
f2 = open(securityGroupFile)
securityData = json.load(f2)
os.system('aws ec2 create-key-pair --key-name script-admin-key-pair > script-admin-key-pair.pem')
buildCommand = "aws ec2 run-instances --image-id {} --count 1 --instance-type t2.micro --key-name script-admin-key-pair --security-group-ids {} --tag-specifications 'ResourceType=instance,Tags=[{{Key=Name,Value=script-admin}}]' > admin-instance-details.json".format(configData['ami-id'],securityData['GroupId'])
os.system(buildCommand)
f3 = open('admin-instance-details.json')
instanceData = json.load(f3)
iamCommand = "aws ec2 associate-iam-instance-profile --instance-id {} --iam-instance-profile Name=script-admin-profile".format(instanceData['Instances'][0]['InstanceId'])
os.system(iamCommand)
